//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesWebiste_V01
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_movie
    {
        public int order_id { get; set; }
        public int movie_id { get; set; }
    
        public virtual movie movie { get; set; }
        public virtual order order { get; set; }
    }
}
